
import java.awt.FlowLayout;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;


public class KritPanel extends javax.swing.JPanel {

    /**
     * Creates new form KritPanel
     */
    public KritPanel(JFrame frame, int countVert, int countKrit) {
        
        this.countVert = countVert;
        this.countKrit = countKrit;
        this.frame = frame;
        /*this.setVisible(true);
        frame.setVisible(true);
        frame.setSize(600, 500);
        frame.setResizable(false);
        this.setLayout(new FlowLayout());*/
        
        initComponents();
        this.setVisible(true);
        jTable1.getColumnModel().getColumn(0).setHeaderValue((""));
        TableColumn column = jTable1.getColumnModel().getColumn(0);
        column.setPreferredWidth(20);
        TableModel model = jTable1.getModel();
        
        //Заполнение названий столбцов
        for (int j = 1; j<=countKrit; j++){
            jTable1.getColumnModel().getColumn(j).setHeaderValue((j));
            column = jTable1.getColumnModel().getColumn(j);
            column.setPreferredWidth(20);
        }
        
        //Заполнение названий строк
        for (int i = 0; i<countVert; i++){
            model.setValueAt(i+1, i, 0);
        }
        frame.setSize(600, 500);
        frame.setResizable(false);
        jTable1.getTableHeader().resizeAndRepaint();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(countVert,countKrit+1);
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTable1);
        //jScrollPane1 = new JScrollPane(jTable1, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        jLabel2.setText("Введите критерии для каждой вершины");

        jButton1.setText("Далее");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton1)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ResultPanel rpanel = new ResultPanel(frame, countVert, countKrit);
        //SecondSecondPanel sspanel = new SecondSecondPanel(frame);
        this.removeAll();
        this.updateUI();
        //this.updateUI();
        frame.remove(this);
        frame.add(rpanel);   
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private int countVert;
    private int countKrit;
    private JFrame frame;
}
