
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author goodspeed
 */
public class MatrixPanel extends javax.swing.JPanel {

    public MatrixPanel() {
        initComponents();
        jTable1.getColumnModel().getColumn(0).setHeaderValue((""));
        TableColumn column = jTable1.getColumnModel().getColumn(0);
        column.setPreferredWidth(20);
        TableModel model = jTable1.getModel();
        
        //Заполнение названий столбцов
        for (int j = 1; j<=count; j++){
            jTable1.getColumnModel().getColumn(j).setHeaderValue((j));
            column = jTable1.getColumnModel().getColumn(j);
            column.setPreferredWidth(20);
        }
        //Заполнение матрицы
        for (int i = 0; i<count; i++)
        {
            for (int j = 1; j<=count; j++)
            {
                model.setValueAt(0, i, j);
            }
        }
        //Заполнение названий строк
        for (int i = 0; i<count; i++){
            model.setValueAt(i+1, i, 0);
            model.isCellEditable(i, 0);
        }
        
        jTable1.getTableHeader().resizeAndRepaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(count,count+1);

        jScrollPane1.setViewportView(jTable1);
        //jScrollPane1 = new JScrollPane(jTable1, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private int count = 50;
}

